---
- name: prepare nomad server configuration
  template:
    src: etc/nomad.d/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: 0644

- name: restart nomad
  systemd: 
    name: nomad
    enabled: true
    state: started
