---
- name: lab1nomad1server1
  network:
    eth1:
      ip: 192.168.56.201
  memory: 1024
  cpus: 1

- name: lab1nomad1client1
  network:
    eth1:
      ip: 192.168.56.202
  memory: 1024
  cpus: 1

- name: lab1nomad1client2
  network:
    eth1:
      ip: 192.168.56.203
  memory: 1024
  cpus: 1