---
- name: check if nomad already downloaded
  stat:
    path: /usr/local/bin/nomad
  register: nomad_downloaded

#- name: download nomad
# unarchive:
#    remote_src: true
#    src: https://releases.hashicorp.com/nomad/0.8.7/nomad_0.8.7_linux_amd64.zip
#    dest: /usr/local/bin/
#    owner: root
#    group: root
#    mode: 0755
#  when: nomad_downloaded.stat.exists == false

- name: unpack nomad binary 
  unarchive:
    src: files/nomad_0.10.2_linux_amd64.zip
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
  when: nomad_downloaded.stat.exists == false

- name: prepare nomad systemd configuration
  template:
    src: etc/systemd/system/nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    owner: root
    group: root
    mode: 0644

- name: create nomad configuration directory
  file:
    path: /etc/nomad.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: create nomad data directory
  file:
    path: "{{ nomad_data_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
