---
- name: prepare nomad client configuration
  template:
    src: etc/nomad.d/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: 0644

- name: enable and start nomad
  systemd:
    name: nomad
    enabled: true
    state: started
